// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://uikckgqmgfdjkabgtxqw.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InVpa2NrZ3FtZ2ZkamthYmd0eHF3Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDg2NDAwNjcsImV4cCI6MjA2NDIxNjA2N30.FXi15EPMvpRvwCblhrl1YiQIK9bRX5CM7w98Qx60SPM";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);